### ISSUE TITLE
click is not work in IE

### ISSUE THREAD

**Issue by tamilk0212** [zsusac/ReactHTMLTableToExcel#12]
This Error Showing in Microsoft Edge
ERROR: Unable to get property 'click' of undefined or null reference

**Comment by metju90** [comment]
I had the exact same error. I fixed it. Opened this PR for this fix:
https://github.com/zsusac/ReactHTMLTableToExcel/pull/15

**Comment by jrsanders1** [comment]
@metju90 This fix you have provided here is not working. I've tried on both IE11 and on Edge. Still getting the same error as before.
